In [31]:
import numpy as np

In [32]:
array1 = np.array([1,2,3,4,5,3,5])
print(array1)
print(type(array1))

[1 2 3 4 5 3 5]
<class 'numpy.ndarray'>


dementional arrays

In [33]:
#0- Dementional arrays also called scalars.
array2= np.array(42)
print(array2)
print(array2.ndim)

42
0


In [34]:
# 1-D array have 0-d arrat as the element. most basics and common arrays

array3=np.array([1,2,3,4,5,6])
print(array3)
print(array3.ndim)
print(array3.shape)

[1 2 3 4 5 6]
1
(6,)


In [35]:
#2D array. these are 1d array as its element
array4= np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(type(array4))
print(array4)
print(array4.ndim)

<class 'numpy.ndarray'>
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2


In [36]:
array5= np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(array5)
print(array5.ndim) # 3 denetionla arrays

print(array5[:3])

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


to check the number of demetions your array has

In [37]:
print(array2.ndim)
print(array3.ndim)
print(array4.ndim)
print(array5.ndim)

0
1
2
3


assessing index of a numpy array

In [38]:
print(array4[0])
print(array4[1])
print(array4[0] + array4[1])

add_arr= np.array([])

[1 2 3]
[4 5 6]
[5 7 9]


Arthimetic Operation

In [39]:
sum= array3 + 1
product = array3 *2
print(sum)
print(product)

[2 3 4 5 6 7]
[ 2  4  6  8 10 12]


In [40]:
#.mean()
#.min()
#.max()
#.sum

sum = np.sum(array3)
min = np.min(array3)
max=np.max(array3)
average = np.mean(array3)

print(sum)

21


In [41]:
multidemension_borodcast= array4 *2
print(multidemension_borodcast)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]


In [54]:
# shapping with numpy array
print(array4.shape)
print(array5.shape)
print(np.shape(array4))
print(np.shape(array3))

(4, 3)
(2, 2, 3)
(4, 3)
(6,)


In [52]:
#two solution will work the samw
print(np.reshape(array3, (2,3)))
#print(array3.reshape(2,3))


[[1 2 3]
 [4 5 6]]


In [62]:
print(np.reshape(array3, (3,2)))

[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [61]:
print(array3)
print(array3.transpose())

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [60]:
# transposing Arrays
print(array4)
print(array4.transpose())

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


printing booloon values

In [66]:
a = np.array([1,2,3,4,5])
b = np.array([2,2,3,3,5])

c= a==b
print(c)

[False  True  True False  True]


In [71]:
a = np.array([True, True, False, False])
b= np.array([True, False, True, False])

c = np.logical_and(a,b)
d= np.logical_or(a,b)
e= np.array_equal(a,b) # check if all elements are equal
print(c)
print(d)
print(e)

[ True False False False]
[ True  True  True False]
False


In [74]:
a= np.array([3,10,7,6,8,31,2,5])
b= np.sort(a) # sorts in order
c= np.sort(a)[::-1] #sort backwards
print(b)
print(c)

[ 2  3  5  6  7  8 10 31]
[31 10  8  7  6  5  3  2]
